name: "Build"

env: # Workflow level environment variables.
  workflow_var: 'Workflow variable value'
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
        default: 'HaCo'
      country:
        description: 'Country'
        required: false

jobs:
  greet_user:
    runs-on: ubuntu-latest
    steps:
    - name: Greet user
      run: echo "Hi, ${{ github.event.inputs.name }} from ${{ github.event.inputs.country }}"

  environment_variables:
    runs-on: ubuntu-latest
    env: # Job level environment variables.
      job_var: "Job variable value"
    steps:
    - name: Print initial variables
      run: |
        echo "Variable workflow_var is [$workflow_var]"
        echo "Variable job_var is [$job_var]"
        echo "Variable step_var is [$step_var]"
      env: # Step level environment variables.
        step_var: "Step variable value"
    - name: Overwrite workflow and job variables
      run: | 
        echo "::set-env name=workflow_var::Overwritten workflow variable value"
        echo "::set-env name=job_var::Overwritten job variable value"
    - name: Create new variable
      run: echo "::set-env name=new_var::Entirly new variable"
    - name: Print final variables
      run: |
        echo "Variable workflow_var is [$workflow_var]"
        echo "Variable job_var is [$job_var]"
        echo "Variable step_var is [$step_var]"
        echo "Variable new_var is [$new_var]"

  build:
    runs-on: ubuntu-latest
    # Create a dependency because by default all jobs run in parallel
    needs: greet_user
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so  your job can access it.
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Start build for workspace $GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -hal
      # Nameless run, so the first line will become the run name
      - run: |
          cmake --version
          make --version
          echo "End of build for workspace $GITHUB_WORKSPACE"
