name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
        default: 'HaCo'
      country:
        description: 'Country'
        required: false

jobs:
  greet_user:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hi, ${{ github.event.inputs.name }} from ${{ github.event.inputs.country }}"

  build:
    runs-on: ubuntu-latest
    # Create a dependency because by default all jobs run in parallel
    needs: greet_user
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so  your job can access it.
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Start build for workspace $GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -hal
      # Nameless run
      - run: |
          cmake --version
          make --version
          echo "End of build for workspace $GITHUB_WORKSPACE"
